### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by gaurav** [NCTraCSIDSci/clark#23]
Hi there! I noticed that one of the links in the README file is broken:

> To download the CLARK! executable without having to package it from source yourself, go to [the NC TraCS website](https://tracs.unc.edu/index.php/tracs-resources/sharehub/category/2-informatics) and download the CLARK zip file. (A demo dataset is also included.)

This link currently gives a 404 error. Could you please fix that? Thanks so much!

**Comment by kennethmorton** [comment]
Thanks for the heads up. This has been resolved.
