### ISSUE TITLE
Support python 3.8

### ISSUE THREAD

**Issue by maximusunc** [NCTraCSIDSci/clark#7]
The application currently doesn't fully support python 3.8. The newer version of python requires newer versions of numpy, sklearn, and scipy, and those in turn break pyinstaller which doesn't support 3.8 yet. (https://github.com/pyinstaller/pyinstaller/issues/4311) Once pyinstaller is updated, we can revisit.

**Comment by maximusunc** [comment]
This issue (https://github.com/scikit-learn/scikit-learn/issues/15899) might help as well, when attempting to build, the process would complete and we could open the application, but the server would fail to initialize because we were missing a sklearn dll (vcomp140.dll).

**Comment by maximusunc** [comment]
[pyinstaller](https://pypi.org/project/pyinstaller/) >= 4.1 now supports python 3.8. Further updates are required to make sure all dependencies are up to date and work with the new python version.

**Comment by kennethmorton** [comment]
We have now pumped to pyinstaller 4.3 and tested everything with python 3.8. All is well.

**Comment by kennethmorton** [comment]
We have now pumped to pyinstaller 4.3 and tested everything with python 3.8. All is well.
